// <auto-generated />
using System;
using LeaveRequestAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeaveRequestAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210919072153_request-end-date-null")]
    partial class requestenddatenull
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeaveRequestAPI.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = "eulee",
                            FirstName = "Eugene",
                            IsSupervisor = false,
                            LastName = "Lee",
                            SupervisorId = "nichaud"
                        },
                        new
                        {
                            EmployeeId = "nichaud",
                            FirstName = "Nishchal",
                            IsSupervisor = true,
                            LastName = "Chaudhary",
                            SupervisorId = ""
                        });
                });

            modelBuilder.Entity("LeaveRequestAPI.Models.EmployeeAccrual", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("AccrualType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("EmployeeId", "AccrualType");

                    b.ToTable("EmployeeAccruals");

                    b.HasData(
                        new
                        {
                            EmployeeId = "eulee",
                            AccrualType = "Vacation",
                            Hours = 112.5m
                        },
                        new
                        {
                            EmployeeId = "eulee",
                            AccrualType = "Personal Leave",
                            Hours = 36m
                        },
                        new
                        {
                            EmployeeId = "eulee",
                            AccrualType = "Sick Leave",
                            Hours = 785.8m
                        },
                        new
                        {
                            EmployeeId = "nichaud",
                            AccrualType = "Vacation",
                            Hours = 96.4m
                        },
                        new
                        {
                            EmployeeId = "nichaud",
                            AccrualType = "Personal Leave",
                            Hours = 42m
                        },
                        new
                        {
                            EmployeeId = "nichaud",
                            AccrualType = "Sick Leave",
                            Hours = 320.3m
                        });
                });

            modelBuilder.Entity("LeaveRequestAPI.Models.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlternateApproverId")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("ApproveBy")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("ApproveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("InAt")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool>("IsMultiDays")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveAt")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("LeaveTimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("LeaveRequestAPI.Models.EmployeeAccrual", b =>
                {
                    b.HasOne("LeaveRequestAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeaveRequestAPI.Models.LeaveRequest", b =>
                {
                    b.HasOne("LeaveRequestAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
